### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by cheap-glitch** [Plazide/fauna-gql-upload#11]
It would be nice going forward to have some GitHub releases for the new versions.

I know it's some extra menial work, but it's always nicer to have even just a quick changelog with mentions of potential breaking changes than having to dig through the commit log. Also that way users can be notified of new releases through GitHub.

Keep up the good work! :+1:

Edit: you might also consider adding a description and some tags to make the repo more discoverable.

**Comment by Plazide** [comment]
Yes, absolutely. The only reason why I haven't done releases before is because I thought it to be unnecessary since there has been like two watchers up until now.

Since you are asking for it, I will definitely start doing releases with every new NPM publish.

And yeah, I'll add a description and some tags, thanks for the tip.
