### ISSUE TITLE
field: ["ref"] upload: validation failed: document data is not valid

### ISSUE THREAD

**Issue by dotnetspec** [Plazide/fauna-gql-upload#23]
System info:
VSCode:
```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:50.094Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-66-generic
```

I've defined an index:
```
const UserFindById = {
  name: "user_find_by_id",
  source: Collection("User"),
  unique: false,
  terms: [
    {
      field: ["ref"]
    }
  ]
};

export = UserFindById;
```
This gives me:
```
❌ Failed to upload indexes

Error uploading indexes
validation failed: document data is not valid.
Failures
invalid index: Index sources, terms, values, and partition count may not be updated.
field:
```
If I define with:
```
field: ["ref", "ref"]
```
it uploads without issue. However, correct me if I'm wrong, this won't work because it results in the index term being
```
ref.ref 
```
(which it does) instead of just 
```
ref
```
How can I upload just
```
field: ["ref"]
```
so that my terms is set to just 'ref' in Fauna?
Thanks ...

**Comment by Plazide** [comment]
Hi,

That error: `invalid index: Index sources, terms, values, and partition count may not be updated.` is caused by trying to update an index's source, terms, or values. This is a limitation with Fauna.

What you need to do is delete the index, wait 60 seconds, and then upload again with your terms set as `field: ["ref"]`. I am planning on adding a feature that does this automatically for you. You can track that in issue #22.

You can delete the index by either going to the dashboard and deleting it from there, or by running using the shell. If you want to delete the index through the shell, you can run the following. 

*Keep in mind that you need the `fauna-shell` npm package installed globally for this to work*

```sh
fauna shell --secret <the secret you use with `fauna-gql-upload`>
```

Then just delete the index:
```sh
> Delete(Index("user_find_by_id"))
```

Then wait 60 seconds and upload your resources again.

Hope that helps.

**Comment by dotnetspec** [comment]
Thanks, yes, that fixed it
