### ISSUE TITLE
Feature: Allow loading custom `.fauna.json` file

### ISSUE THREAD

**Issue by Vadorequest** [Plazide/fauna-gql-upload#26]
I'd like to have 2 different `envPath` (e.g: `.env.local.production` and `.env.local.staging`) which would both define `FAUNADB_SERVER_SECRET_KEY` pointing to 2 different Fauna DBs (staging, production)

Right now, I don't think I can achieve that because the `.fauna.json` path is hardcoded and can't be changed.

Could an option to `fauna-gql` script could be added to allow specifying a custom config file?

https://github.com/Plazide/fauna-gql-upload/blob/746d86acc377773a6576f781caa8d1a474ea1450/src/util/getConfig.ts#L44

**Comment by Plazide** [comment]
Yes, that sounds like a good idea.

It would also be nice to have command-line options for each specific property in `.fauna.json`, so that you wouldn't need multiple configs with just one or two different options. In your case, you could simply add a script like this:

```sh
fgu --envPath .env.local.production
```

And to specify a different config altogether, you would do:

```sh
fgu --config .fauna.prod.json
```

I'll add this ASAP.

**Comment by Plazide** [comment]
Okay,

Custom path for config file is now supported with version `2.1.0`, simply use:
```sh
fgu --config custom.config.json
``` 
You can also pass in command-line options for every property supported in the config file. So you could specify a custom environment file with the following:

```sh
fgu --envPath .custom.env
```

**Comment by Vadorequest** [comment]
Awesome, thank you! I'll try it out ASAP

**Comment by Vadorequest** [comment]
Works like a charm!
