### ISSUE TITLE
Possible issue with esbuild and node 15.3.0+?

### ISSUE THREAD

**Issue by ry5n** [Plazide/fauna-gql-upload#30]
Hi! Thanks for taking the time to build something like this package :D

I’m using using native es modules in node (16.2.0) with `"type": "module",` in my package.json.

When I run the upload script, I’m getting `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module` when the package is trying to read my Fauna resource files.

I’m no expert, but I think it’s because of esbuild. If I remove `"type": "module"` from my package.json, the upload succeeds.

This works for now, since all I have in this package folder is the fauna resources, but I can imagine this causing conflicts sooner or later. Any advice?

**Comment by Plazide** [comment]
Hi Ryan! Glad you like the package.

Thanks for reporting this issue. After some testing, it seems that this error occurs in earlier version of node as well. You are correct, the issue is caused by esbuild outputting files in CommonJS, while `"type": "module"` infers that files should use `module` syntax.

My solution to this will be to use a `.cjs` extension on the output files. This will work both with and without `"type": "module"`.

I'll update sometime next week along with some other changes. I'll leave a comment on this issue to let you know when it's available.

**Comment by ry5n** [comment]
Thanks @Plazide!

**Comment by Plazide** [comment]
Hey @ry5n

A new version has been published to NPM which includes the fix for this!

Let me know if it works for you!

**Comment by ry5n** [comment]
It works! Thanks again :)
