### ISSUE TITLE
Default GraphQL endpoint wrong for new FaunaDB accounts

### ISSUE THREAD

**Issue by alexarutian** [Plazide/fauna-gql-upload#37]
Thanks for this utility!

I was setting this up using the instructions, and kept getting "invalid database secret." It turns out that current FaunaDB accounts have a different endpoint than in the past. util/env.ts is setting the endpoint to https://graphql.fauna.com, but that is out of date and it could be https://graphql.us.fauna.com/import or https://graphql.eu.fauna.com/import, depending on where the user is.

Since this URL varies by user, changing the instructions to require the URL in the .env is the simplest fix I can think of. You could point users here:

https://docs.fauna.com/fauna/current/api/graphql/endpoints

**Comment by Plazide** [comment]
Hi, thanks for reporting!

I was not aware that Fauna had added different endpoints for different regions. This issue has probably existed for quite a while then. Really appreciate the report as I haven't created a new database since they added region groups.

While adding an environment variable is a good idea, I would prefer a solution where it is added as an option to `.fauna.json`. This would allow the user to customize the region using a command-line option when running in different environments.

An important part about this tool for me is the ability to create a schema and run upload, and that's it. In other words, the simplicity of using it. It would therefore be ideal if the endpoint had a default value so that we don't require more settings than necessary, but as you say, the endpoint varies by user. Setting a default value is then going to work for some and break everything for others.

One solution might be to try sending requests to all the endpoints and check which one returns without an "invalid database secret" error, and then use that endpoint for uploading resources. If the user has specified the region option, we just use that and don't go through the process of trying endpoints.

Thanks again, and please share any concerns you might have about my proposed solution.

**Comment by alexarutian** [comment]
I really like that idea. No concerns from me. Thanks for the response and I've found this tool super useful, appreciate the work that went into it!

**Comment by Plazide** [comment]
Hey,

Just wanted to let you know that I've implemented my proposed solution, and it is available in version `2.4.0`. 

Thanks for reporting!
