### ISSUE TITLE
Errors should throw

### ISSUE THREAD

**Issue by winghouchan** [Plazide/fauna-gql-upload#39]
# Problem

`fauna-gql-upload` sometimes gets into error states without returning an error exit code (although it does log errors). These error states can be found everywhere the [`status` function](https://github.com/Plazide/fauna-gql-upload/blob/b5fb6d3392ba2aa49f158ca81692d564501bb222/src/util/logger.ts#L7) is called with its `status` parameter being `"error"` but no error is thrown or exit error code set.  This is an issue because in cases where `fauna-gql-upload` is run programmatically, the caller cannot appropriately respond.

## A test case

Here's a test case based on one location where the `status` function is called with its `status` parameter being set to `"error"` ([reference](https://github.com/Plazide/fauna-gql-upload/blob/b5fb6d3392ba2aa49f158ca81692d564501bb222/src/lib/schema.ts#L27)) – it's also the easiest error state to reproduce.

### Prerequisites

**`.env`** - Required to navigate past error thrown that environment variable holding the secret cannot be read ([see here](https://github.com/Plazide/fauna-gql-upload/blob/b5fb6d3392ba2aa49f158ca81692d564501bb222/src/util/env.ts#L19))

```txt
FGU_SECRET=anything
```

**`index.js`** - Programmatically runs `fauna-graphql-upload`, exit handler responds to [exit codes](https://en.wikipedia.org/wiki/Exit_status). Exit codes greater than 0 typically denote an error state.

```javascript
import { spawn } from "child_process";

async function runFGU() {
  return new Promise((resolve, reject) => {
    spawn("npm", ["run", "fgu"], { stdio: "inherit" }).on("exit", (code) =>
      (code === 0 || code === null ? resolve : reject)(code)
    );
  });
}

async function test() {
  try {
    await runFGU();
    console.log("Should not run because runFGU errored");
  } catch (error) {
    console.log("runFGU error was caught and handled");
  }
}

test();
```

**`package.json`**

```json
{
  "type": "module",
  "dependencies": {
    "fauna-gql-upload": "^2.4.0",
    "faunadb": "^4.4.1"
  },
  "scripts": {
    "fgu": "fgu"
  }
}
```

### Steps

1. Install dependencies: `npm install`
2. Start Docker container with Fauna image (see [https://docs.fauna.com/fauna/current/integrations/dev](here)).
3. Run script: `node index.js`

### Expected experience

1. `fauna-graphql-upload` logs an error saying: "Cannot find schema at ./fauna/schema.graphql".
2. Process running `fgu` exits with an error code (exit code greater than 0). The exit handler will receive the exit code and can appropriately handle it by checking if it is 0.
3. `"runFGU error was caught and handled"` is logged; `"Should not run because runFGU errored"` is not logged.

### Actual experience

1. `fauna-graphql-upload` logs an error saying: "Cannot find schema at ./fauna/schema.graphql".
2. Process running `fgu` exits with the success code (exit code being 0). The exit handler will receive the exit code but cannot appropriately determine it is an error because the process reported it was a success.
3. `"runFGU error was caught and handled"` is not logged; `"Should not run because runFGU errored"` is logged.

**Comment by winghouchan** [comment]
A solution could be setting [`process.exitCode`](https://nodejs.org/api/process.html#processexitcode_1) to a value greater than 0, typically 1, at the appropriate places.

**Comment by Plazide** [comment]
Hey,

Thanks for the detailed report. I would just like to note that calling `fauna-gql-upload` programmatically can be done by doing `import { upload } from "fauna-gql-upload"` and then `upload({ resources: [] })`. This is not fully supported, though, which is why it's not mentioned in the documentation. It suffers from the same problem that you are reporting.

While setting `process.exitCode` would be sufficient for the time being, it would not be enough for handling the planned programmatic usage. In that case, just throwing errors would probably be the best way to do it, and then let the developer take care of handling those errors. Since throwing inherently returns a non-zero exit code, it would also solve the use case you described above.

I'll address this issue when implementing support for programmatic usage, which will be soon™.

Again, thanks for the report!

**Comment by winghouchan** [comment]
> I would just like to note that calling fauna-gql-upload programmatically can be done by doing `import { upload } from "fauna-gql-upload"` and then `upload({ resources: [] })`.

This is really good to know, thanks. Simplifies my code a bit!

> While setting `process.exitCode` would be sufficient for the time being, it would not be enough for handling the planned programmatic usage. In that case, just throwing errors would probably be the best way to do it, and then let the developer take care of handling those errors. Since throwing inherently returns a non-zero exit code, it would also solve the use case you described above.

This sounds perfect 👍🏼 I'll update the title of this issue to "Errors should throw" to reflect this.

Is there a lot of required work for supporting programmatic usage? Curious to see if it's possible for incremental delivery and also if other folks could potentially contribute (I'd be happy to). For this issue, could it just be identifying locations to throw (a starting point could be every place where `status` is called with `"error"`) and designing error interfaces?

**Comment by Plazide** [comment]
I don't expect there to be too much work in implementing programmatic usage. The main building blocks are already in place, such as the upload function. We just need to expose functionality that is already supported.

I have no written requirements for what programmatic usage would entail, just a vague idea of how it could work. It might be a good idea to start discussion around this topic in another issue. That might lead to a more concrete plan on how it should work and what functionality should be exposed.

**Comment by winghouchan** [comment]
I'll head to #41 to chat about programmatic usage.

In the meantime, I think this is a separate piece of work. Actual errors are still necessary with the command line interface. For example, if I'm running `fgu` in a CI/CD pipeline and it fails, the pipeline run cannot report that is has succeeded.

**Comment by Plazide** [comment]
Yes, I agree. I see two possible ways to handle this:

1. The simplest way to handle this is just to throw inside the `status()` function whenever the `status` argument is equal to `"error"`. This would be semantically confusing, since you wouldn't expect a function named `"status()"` to cause the application to halt.
2. The slightly more work intensive way is to, as you have stated, add throw statements following any call to the `status()` function where the `status` parameter is `"error"`. 

The solution to this is impacted by the implementation of programmatic usage. Since this issue can be resolved earlier than the programmatic usage, it might be best to use option 1. Programmatic usage will require refactoring regardless of what we do here. Hence, the quicker solution might be enough in the meantime.

What do you think?

**Comment by winghouchan** [comment]
Yes, agreed on your assessment here 👍🏼

**Comment by Plazide** [comment]
Okay, it took me some time to get around to this, but it's done now. As of version `2.4.3` errors throw and the package returns a non-zero exit code.

Thanks for opening the issue 👍
